### PR TITLE
Added configurable status text.

### PR DESCRIPTION
**Pull request by lobbin**
Added setting for configuring the status output text.

### CODE REVIEW

**Comment by derrickpelletier** [comment]
Hey, thanks. I'll merge this but can you change that setting from being called `text` to being called `label`? 
I just think `text`sounds a bit vague, though the difference is negligible.

**Comment by lobbin** [comment]
Sure, will do :)

**Comment by lobbin** [comment]
Fixed.

**Comment by derrickpelletier** [comment]
thanks, i'll update npm later today

**Comment by lobbin** [comment]
Looks like the updated npm is missing the feature?

**Comment by derrickpelletier** [comment]
Ah, you're right. My bad.

Should be updated now :+1:

**Pull request merged**
